version: '3.1'

services:
  dolphin:
    build: .
    restart: always
    ports:
      - 8081:80
    environment:
      VIRTUAL_HOST: localhost
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 5506:3306
    environment:
      MYSQL_ROOT_PASSWORD: dolphin_root_password
      MYSQL_DATABASE: dolphin
      MYSQL_USER: dolphin_user
      MYSQL_PASSWORD: dolphin_password
